spring.application.name=alex-shop-backend
spring.datasource.url=jdbc:mysql://localhost:3306/alex_shop
spring.datasource.username=root
spring.datasource.password=a1031806
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true